# Generated by Django 4.1.2 on 2023-03-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
