# Generated by Django 4.1.2 on 2023-03-13 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_secondarycomment_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='background_color',
        ),
    ]
