# Generated by Django 4.1.2 on 2023-03-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_profileuser_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_approved',
            field=models.BooleanField(default=False),
        ),
    ]
