# Generated by Django 4.1.2 on 2023-03-17 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_post_post_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondarycomment',
            old_name='secondary_comment',
            new_name='secondary',
        ),
    ]
